### ISSUE TITLE
How to download and build pt-hub for Aarch64?

### ISSUE THREAD

**Issue by thexile** [pi-top/Device-Management#12]
It would be great if anyone could point out how to go about downloading and building pt-hub source code. I am trying to get it to work on an ODROID-C2 in a pi-top v1 running Ubuntu Mate 16.04 (Aarch64).

**Comment by m-roberts** [comment]
Hey thexile!

pt-hub is a dummy package which installs `pt-device-manager` and either `python3-pt-hub` or `python3-pt-hub-v2` depending on which generation of pi-top hardware you have. The original pi-top and pi-topCEED use `python3-pt-hub`, and the current pi-top uses `python3-pt-hub-v2`.

We will be releasing the source code on Github in the near future. If you do not wish to wait, I recommend that you download the packages you need, extract them, and see what they are doing. The `.deb` files can be found [here](http://archive.raspberrypi.org/debian/pool/main/p/).

There is nothing to build, as this system is written in Python. There are simply files that are installed onto the filesystem. These are not guaranteed to work on any other operating system except Raspbian and pi-topOS on a Raspberry Pi. ODROID has its own GPIO libraries. If, however, you replace all Raspberry Pi-specific libraries to using ODROID's GPIO library, it seems like you should be able to port it over to Aarch64.
