### ISSUE TITLE
pi-top rev 2 with Raspbian stretch shows error during shutdown

### ISSUE THREAD

**Issue by rricharz** [pi-top/Device-Management#14]
I have installed pt-hub on a fresh copy of Raspbian on the pi-top rev 2 and get the following error message during shutdown:
[FAILED] Failed to start pi-topHUB-v1.service shutdown announcement

**Comment by m-roberts** [comment]
Does it leave anything more significant in the journal?

**Comment by rricharz** [comment]
I see the following errors from time to time during shutdown in log of the device manager. Any other log that I should inspect?

[errors.txt](https://github.com/pi-top/Device-Management/files/1536168/errors.txt)

**Comment by rricharz** [comment]
This is what poweroff-v1 logs:
-- Reboot --
Dec 06 16:22:35 pitop2 systemd[1]: Starting pi-topHUB v1 shutdown announcement...
Dec 06 16:22:37 pitop2 poweroff-v1[1352]: Unable to open SPI device: No such file or directory
Dec 06 16:22:37 pitop2 poweroff-v1[1352]: poweroff version 1.0
Dec 06 16:22:37 pitop2 systemd[1]: pt-poweroff-v1.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 16:22:37 pitop2 systemd[1]: Failed to start pi-topHUB v1 shutdown announcement.
Dec 06 16:22:37 pitop2 systemd[1]: pt-poweroff-v1.service: Unit entered failed state.
Dec 06 16:22:37 pitop2 systemd[1]: pt-poweroff-v1.service: Failed with result 'exit-code'.

And this is what poweroff-v2 logs:
-- Reboot --
Dec 06 16:22:35 pitop2 systemd[1]: Starting pi-topHUB v2 shutdown announcement...
Dec 06 16:22:36 pitop2 systemd[1]: Started pi-topHUB v2 shutdown announcement.

Why are both services active?

**Comment by m-roberts** [comment]
This was a less-than-satisfactory design decision that was implemented due to constraints on development at the time. It would be good to have a chat with you about possible solutions.

**Comment by rricharz** [comment]
I think we are talking about 2 different issues here. One shows up in the log of the device manager, the other one in the log of poweroff-v1 if spi is turned off on a pi-top rev 2.

The red error message during the shutdown (second issue) is not acceptable for high quality software. The best workaround depends on the situation:

1. If you want to use the same SD card on pi-topCEED, pi-top rev 1 and pi-top rev 2:
    Make sure that spi is enabled in Menu -> Preferences -> Raspberry Pi Configuration
 
2. If you use the SD card only on a pi-top rev 1 and pi-topCEED:
    Open a terminal and type _sudo systemctl disable pt_poweroff-v2_

3. If you use the SD card only on a pi-top rev 2:
    Open a terminal and type _sudo systemctl disable pt_poweroff-v1_

I propose to add automatic disabling and enabling to the set_device_id() method of the class ShutdownManager in ptdm_shutdown_manager.py. That would ensure that the proper poweroff is called and no unnecessary error messages or confusing log entries are produced. Do you want me to write and test this?

The first issue (problem to get i2c mode) is much more complex, but I am willing to help if you send me your thoughts using email.

**Comment by m-roberts** [comment]
I'm still a bit confused - automatic enabling/disabling in `set_device_id()` to prevent both poweroff scripts from running sounds good to me. Could you help me to understand what you consider to be the other problem?

**Comment by rricharz** [comment]
I haven't figured out what the second error means and whether it has any consequences. This is what the log shows sometimes when the pi-top is shut down:

Dec 06 16:22:35 pitop2 systemd[1]: Stopping pi-top device auto-detection and configuration daemon...
Dec 06 16:22:35 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Stopping device manager...
Dec 06 16:22:35 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Unable to verify I2C mode. Command '['/usr/bin/raspi-config', 'nonint', 'get_i2c']' 
Dec 06 16:22:35 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Traceback (most recent call last):
                                                                            File "/usr/lib/python3/dist-packages/ptcommon/sys_config.py", line 69, in get_i2c_
                                                                              i2c_output_str = str(_SystemCalls._get_cmd_resp(_SystemCalls.GET_I2C_CMD_ARR)).r
                                                                            File "/usr/lib/python3/dist-packages/ptcommon/sys_config.py", line 33, in _get_cmd
                                                                              resp = check_output(cmd_arr)
                                                                            File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
                                                                              **kwargs).stdout
                                                                            File "/usr/lib/python3.5/subprocess.py", line 398, in run
                                                                              output=stdout, stderr=stderr)
                                                                          subprocess.CalledProcessError: Command '['/usr/bin/raspi-config', 'nonint', 'get_i2c
Dec 06 16:22:35 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Closing responder socket...
Dec 06 16:22:36 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Stopping idle time monitor...
Dec 06 16:22:36 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Stopping peripheral manager...
Dec 06 16:22:36 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Stopping hub manager...
Dec 06 16:22:36 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Unblanking screen
Dec 06 16:22:36 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Stopping hub module...
Dec 06 16:22:37 pitop2 /usr/lib/pt-device-manager/pt-device-manager[382]: Hub connection loop stopped

**Comment by m-roberts** [comment]
I think that might simply be happening if it's in the middle of a system call when it's exiting?

**Comment by rricharz** [comment]
Yes, indeed. I just checked. It happens if a python skript talking to the led matrix of the pi-topPULSE is running when the shutdown is initiated. No real issue if it does not affect the proper shutdown. But the problem of pt_poweroff-v1 resulting in a visible red error during shutdown if spi is turned off on the pi-top version 2 needs to be fixed.
