### ISSUE TITLE
pt-device-manager: correctly detect devices when starting with I2C disabled

### ISSUE THREAD

**Issue by m-roberts** [pi-top/Device-Management#20]
*Steps to test*:
1) Stop device manager
2) Disable I2C
3) Start device manager
4) Does device ID work?

*More detail*:
* Stop device manager: `sudo systemctl stop pt-device-manager`
* Disable I2C by running `sudo raspi-config`, `Interfacing Options`, `I2C`, `No`
* Start device manager: `sudo systemctl start pt-device-manager`
* Check device ID: `pt-devices`

*Expected behaviour*:
Previously, this would have resulted in ALL hardware saying "pi-topCEED". The new behaviour should be that the device is always correctly identified.

*Possible new/outstanding issues to look into*:
* Raspberry Pi without a GPIO cable attached might be identified as a pi-topCEED.

**Comment by m-roberts** [comment]
https://github.com/pi-top/Device-Management/commit/b88bd56e5bc006dcc20749f8a81bfc5359e61779

**Comment by m-roberts** [comment]
Needs testing; `initialise` might not be the best place for this

**Comment by m-roberts** [comment]
https://github.com/pi-top/pt-device-manager-deb/commit/a05d55d8afd24bd490936f8af2bd5d77efb691d2

**Comment by m-roberts** [comment]
Now using python3-pt-common for getting and setting I2C
https://github.com/pi-top/Device-Management/commit/afa12aba10007118e7aa9b1f34c5a9312f4fc7a5

**Comment by m-roberts** [comment]
@Eliz4567 This is now ready for testing.

Note to all: if this passes testing, [this PR](https://github.com/pi-top/Device-Management/pull/21) needs to be closed.

**Comment by Eliz4567** [comment]
QA test - failed.

Tested on a pi-topV2. System still states that the host device is a pi-topCEED.
@m-roberts

**Comment by m-roberts** [comment]
@Eliz4567 This test was primarily to ensure that new users will get the correct data even if I2C was initially switched off. What has been identified here appears to only be a problem when I2C is disabled while the device manager is running. I have revised the steps to disable the device manager before modifying the I2C state, as this better reflects the system state we are targeting.

I will create a separate issue for disabling I2C while the device manager is running.

**Comment by Eliz4567** [comment]
QA test - passed
