### ISSUE TITLE
Where is pt-display now?

### ISSUE THREAD

**Issue by codepope** [pi-top/Device-Management#30]
I was installing pt-device-manager on Standard Raspbian and noted recent changes fixed an issue with pt-display by moving it to another module. This means it isn't installed, but... where is it now?

**Comment by m-roberts** [comment]
Hi - Apologies for the delay.
There was UI-altering code that was present in `pt-desktop` (relating to scaling UI components according to screen resolution), which has now been moved to `pt-display`.

`pt-desktop` is defined as 'recommended' by pt-device-manager - i.e. non-essential. However, it is used for notifying the user if a reboot is required, for example.

You do not need `pt-display`, as this is part of the UI side of pi-topOS. This should not affect anything to do with the device management.
