### ISSUE TITLE
Sound skipping once a second with pi-topSPEAKER

### ISSUE THREAD

**Issue by adam-burns** [pi-top/Device-Management#32]
Linux pi-top 4.14.52-v7+ #1123  SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
pt-device-manager	1.0.7-1
hub v1
pi-topSPEAKER
pi-topPROTO

Default behaviour observed: using clementine playing stream, sound skipping once a second. :(

journalctl -fu pt-device-manager
 Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Enabling peripheral: pi-topSPEAKER-v1-Mono
 Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: MS since idle: 1744
 Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Initialising speaker (mode m)
 Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Enabling write to pi-topSPEAKER (115)
 Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Writing config data to pi-topSPEAKER
Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Disabling write to pi-topSPEAKER (115)
Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Adding enabled peripheral: pi-topSPEAKER-v1-Mono
Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Publishing PUB_PERIPHERAL_CONNECTED 2
Aug 05 21:01:01 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Unblanking screen
Aug 05 21:01:03 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Enabling peripheral: pi-topSPEAKER-v1-Mono
Aug 05 21:01:03 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Initialising speaker (mode m)
Aug 05 21:01:03 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Enabling write to pi-topSPEAKER (115)
Aug 05 21:01:03 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Writing config data to pi-topSPEAKER
Aug 05 21:01:03 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Disabling write to pi-topSPEAKER (115)
Aug 05 21:01:03 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Adding enabled peripheral: pi-topSPEAKER-v1-Mono
Aug 05 21:01:03 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Publishing PUB_PERIPHERAL_CONNECTED 2
Aug 05 21:01:03 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Unblanking screen
Aug 05 21:01:04 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Enabling peripheral: pi-topSPEAKER-v1-Mono
Aug 05 21:01:04 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Initialising speaker (mode m)
Aug 05 21:01:04 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Enabling write to pi-topSPEAKER (115)
Aug 05 21:01:04 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Writing config data to pi-topSPEAKER
Aug 05 21:01:04 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Disabling write to pi-topSPEAKER (115)
Aug 05 21:01:04 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Adding enabled peripheral: pi-topSPEAKER-v1-Mono
Aug 05 21:01:04 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Publishing PUB_PERIPHERAL_CONNECTED 2
Aug 05 21:01:04 pi-top /usr/lib/pt-device-manager/pt-device-manager[25412]: Unblanking screen

**Comment by m-roberts** [comment]
Can you confirm that you are still experiencing this?
